version: 2

docker_defaults: &docker_defaults
    docker:
        - image: cypress/browsers:node16.17.1-chrome106-ff105-edge
          environment:
              TERM: xterm
              RECORD_REPLAY_DIRECTORY: /root/project/replay
    working_directory: ~/project/repo

attach_workspace: &attach_workspace
    attach_workspace:
        at: ~/project

install_steps: &install_steps
    steps:
        - checkout
        - restore_cache:
              name: Restore node_modules cache
              keys:
                  - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  - dependency-cache-{{ .Branch }}-
                  - dependency-cache-
                  - cache-{{ checksum "package.json" }}
        - run:
              name: Installing Dependencies
              command: |
                  yarn install --silent
        - save_cache:
              name: Save node_modules cache
              key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
              paths:
                  - ~/.cache
        - persist_to_workspace:
              root: ~/project
              paths:
                  - repo

workflows:
    version: 2
    build_pipeline:
        jobs:
            - build
            - end_to_end:
                  requires:
                      - build
jobs:
    build:
        <<: *docker_defaults
        <<: *install_steps
    # unit_test:
    #     <<: *docker_defaults
    #     steps:
    #         - *attach_workspace
    #         - run:
    #               name: Running unit tests
    #               command: |
    #                   yarn prettier:check
    #                   yarn lint
    #                   yarn type-check
    #                   yarn test:jest
    #                   yarn coveralls
    end_to_end:
        <<: *docker_defaults
        steps:
            - *attach_workspace
            - run:
                  name: Running E2E tests
                  command: |
                      apt update
                      apt install xz-utils
                      yarn global add cypress
                      yarn install --silent
                      yarn cypress install
                      npx @replayio/cypress install
                      RECORD_ALL_CONTENT=1 RECORD_REPLAY_METADATA_FILE=$(mktemp) yarn e2e:replay
            - run:
                name: touch
                when: always
                command: touch /root/.replay/playwright/file
            - run:
                name: ls
                when: always
                command: ls -al /root/.replay/playwright
